### ISSUE TITLE
Request: SD card file sort order

### ISSUE THREAD

**Issue by dgonner** [Ultimaker/Ultimaker2Marlin#125]
The order in which the files on the SD card are presented in the print menu on the Ultimaker 2+ seems to be backwards. Whenever I want to print a file that I just added via Cura, I always have to scroll to the bottom of the list to select my file. Sometimes there are a lot of files on the SD card and scrolling takes a while. The files seem to be orderd by creation date, not modification date. So if I overwrite an older file, it does not display it at the bottom of the list as expected.

My suggestion is to reverse the sort order, with the newest file at the top and sort by file modification date instead of file creation date. This way, the latest modified file appears first when selecting the print menu and it is easier and faster to start a new print.

Dave

**Comment by ckielstra** [comment]
First of all: there is no sorting of the files in the print menu. The order is defined by the sequence as written on the SD-card. New files are added at the end and that's why it appears as if there is a sorting on file creation date. The sequence becomes undefined once you start deleting files.

Because of very tight memory limits it isn't possible to sort the files. The UM3 has lots of memory and can sort.

One recent improvement to the UM3 is that we place the most recent file on top of the list. I'll add this to the wish-list for the UM2.
