### ISSUE TITLE
Feature Request - #define Z_DUAL_STEPPER_DRIVERS 

### ISSUE THREAD

**Issue by juliogdiana** [Ultimaker/Ultimaker2Marlin#127]
Looking to enable dual Z stepper drivers for Ultimaker when you have only one extruder.

Unfortunately my Z stepper crooked and i am looking to use the spare extruder stepper to control the Z axis.

I know it is possible on RAMPS 1.4 but I cant get it to work on Ultimaker board.

I have defined this on adv.h

#define Z_DUAL_STEPPER_DRIVERS

#ifdef Z_DUAL_STEPPER_DRIVERS
  #undef EXTRUDERS
  #define EXTRUDERS 1
#endif

But I am getting error on pinout after verify

Any help will be appreciated

**Comment by ckielstra** [comment]
This isn't a feature request but a standard support question. Please ask those question at the Ultimaker forum since more people there are able to help you.

The Z_DUAL_STEPPER_DRIVERS function seems to be broken in the Ultimaker Marlin. It's not a function we are planning to support and most likely will be removed from a new version.
Easier change for you is go to pins.h and change the first Z-axis to use the pins from the spare motor driver.
In pins.h change:
    #define Z_STEP_PIN         46
    #define Z_DIR_PIN          48
    #define Z_ENABLE_PIN       63

into:
    #define Z_STEP_PIN         36  // 46
    #define Z_DIR_PIN          34  //48
    #define Z_ENABLE_PIN       30  / 63
