### ISSUE TITLE
What's the difference with other Ultimaker/Marlin github library?

### ISSUE THREAD

**Issue by carlosen14** [Ultimaker/Ultimaker2Marlin#135]
Just by looking at the other library [Ultimaker/Marlin](https://github.com/Ultimaker/Marlin), it looks like they both have the same files (except for the marlin simulator).

Is there any significant difference have to be must known?

**Comment by ckielstra** [comment]
Things are confusing indeed, names could have been more specific.
It all started with the same code base and that evolved with a new repository for every new machine released since we wanted to keep development hidden from the public. After product release we could have merged the forked repositories back into the original repository and keep the differences in branches for each product line. We just didn't do that because of higher priorities elsewhere.

Ultimaker/Marlin is for the UM Original, UMO for short
Ultimaker/Ultimaker2Marlin is for the UM2, with separate branches for the UM2 Go and UM2 Extended
Ultimaker/UM2.1-Firmware is for the UM2+, with separate branches for the UM2+ Go and UM2+ Extended
